server:
  port: 8080
spring:
  application:
    name: weather-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    master:
      jdbc-url: 'jdbc:mysql://localhost:3306/weather_db?useSSL=false&characterEncoding=utf8&allowMultiQueries=true'
      username: 'root'
      password: '1234'

  profiles:
    active: dev